image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
- port: 3306
  onOpen: ignore
tasks:
- name: Apache & MySQL
  command: >
    cp .env.example .env;
    cp .htaccess.example .htaccess;
    mariadb-install-db --defaults-extra-file=$GITPOD_REPO_ROOT/gitpod_config/mysql/mysql.cnf --auth-root-authentication-method=normal --datadir=$GITPOD_REPO_ROOT/gitpod_config/mysql/data --user=gitpod --force --verbose;
    mysqld_safe --defaults-file=$GITPOD_REPO_ROOT/gitpod_config/mysql/mysql.cnf --log-error=$GITPOD_REPO_ROOT/gitpod_config/mysql/logs/error.log --general-log-file=$GITPOD_REPO_ROOT/gitpod_config/mysql/logs/mysql.log --datadir=$GITPOD_REPO_ROOT/gitpod_config/mysql/data &
    sleep 5;
    mysql -u root -e "CREATE DATABASE testdb";
    apachectl start;
    multitail $GITPOD_REPO_ROOT/gitpod_config/apache/logs/access.log -I $GITPOD_REPO_ROOT/gitpod_config/apache/logs/error.log -I $GITPOD_REPO_ROOT/gitpod_config/mysql/logs/error.log
- name: Terminal
  command: >
    nvm install 16;
    nvm use 16;
    composer install && php vendor/bin/typo3cms install:setup --no-interaction --database-user-name=root --database-host-name=127.0.0.1 --database-port=3306 --database-name=testdb --use-existing-database --admin-user-name=admin --admin-password=password --site-setup-type=site --web-server-config=apache && php vendor/bin/typo3cms configuration:set SYS/trustedHostsPattern ".*";
    touch $GITPOD_REPO_ROOT/public/typo3conf/ENABLE_INSTALL_TOOL;
    echo "";
    echo "";
    echo "";
    echo "Welcome!";
    echo "";
    echo "Start, stop or review Apache errors:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
  openMode: split-right
vscode:
  extensions:
    - cweijan.vscode-database-client2
    - ms-vscode.vscode-typescript-tslint-plugin
    - dbaeumer.vscode-eslint
    - johnpapa.angular2
    - cyrilletuzi.angular-schematics
    - angular.ng-template
    - ecmel.vscode-html-css
    - bmewburn.vscode-intelephense-client
    - nadim-vscode.symfony-code-snippets
    - donjayamanne.git-extension-pack
    - ikappas.composer
